"""Response schemas for the file-upload endpoint."""
from typing import Any

from pydantic import BaseModel, Field


class FileUploadResponse(BaseModel):
    """Response returned after a successful file upload and extraction."""
    upload_id: str = Field(
        description="MongoDB upload record ID for this upload operation.",
        examples=["69f6432f423c9bfe1bf883a0"],
    )
    user_id: str = Field(
        description="Caller/user identifier provided in the request.",
        examples=["user-123"],
    )
    original_filename: str = Field(
        description="Original client-provided filename.",
        examples=["invoice.pdf"],
    )
    stored_filename: str = Field(
        description="Internal stored filename generated by the service.",
        examples=["61ca05f9-d3e6-4a02-8523-f7806b5411b0.pdf"],
    )
    uploaded_file_s3_key: str = Field(
        description="S3 object key for the originally uploaded source file.",
        examples=["content-extractor/uploads/uuid/uuid.pdf"],
    )
    extension: str = Field(
        description="Normalized extension used by the extraction pipeline.",
        examples=["pdf"],
    )
    extract_media: bool = Field(
        description="Echo of request flag indicating whether media extraction was enabled.",
        examples=[True],
    )
    store_media: bool = Field(
        description=(
            "Echo of request flag indicating whether media was stored in S3 "
            "instead of inline base64."
        ),
        examples=[True],
    )
    content_versions: list[dict[str, Any]] = Field(
        description="Created content versions for this upload; "
        "content_id is used by GET /content and generator service.",
    )
    created_at: str = Field(
        description="ISO-8601 UTC timestamp when upload record was created.",
    )
    updated_at: str = Field(
        description="ISO-8601 UTC timestamp when upload record was last updated.",
    )
